language: go

go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - master

script:
  - make build
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./api/people

notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
